var fs = require("fs");
module.exports={
    'api_route_path':'/',
    'flag_colors':{
        'incurable infectious disease': "#f4ce42",
        'curable infectious disease': "#fc0000",
        'diabetic': "#009933",
        'risk of fall': "#000cff",
        'other':"#ffffff"
    },
    'max_record_per_page':10 ,
    'USER_STATUS':{
        '-99':'ONLINE',
        '0':'OFFLINE',
        false:'OFFLINE',
        '1':'ONLINE',
        true:'ONLINE',
        '2':'BUSY',
        '3':'INVISIBLE',
        '4':'AWAY'
    },
    'ALLOWED_ORIGIN':[
        'http://52.43.126.48', 
        'http://52.43.126.48:3000', 
        'http://52.43.126.48:3001', 
        'http://localhost', 
        'http://127.0.0.1:8080', 
        'http://localhost:8080'
    ],
    'getPrivateKey':function(){
        return fs.readFileSync('./keys/private.pem');
    },
    'getPublicKey':function(){
        return fs.readFileSync('./keys/public.pem');
    },
    'master_models_mapper':{
        icdCodes:'M_IcdCodeDX',
        m_icd9c: 'M_ICD9C',
        m_dataObject: 'M_DataObject',
        drugList: 'M_NDrugMasters',
        m_vital: 'M_Vital',
        m_vitalunit:'M_VitalUnit',
        m_prefix: 'M_Prefix',
        m_country: 'M_Country',
        m_state: 'M_State',
        m_city: 'M_City',
        m_services: 'M_Service',
        m_imaging: 'M_Imaging',
        m_imagingCategory: 'M_ImagingCategory',
        m_wards: 'M_Ward',
        m_procedure: 'M_Procedure',
        m_allergy: 'm_allergy',
        m_clinic: 'M_Clinic',
        m_department: 'M_Department',
        m_flag: 'M_Flag',
        m_poc: 'M_POC_Test',
        M_BloodComponent: 'M_BloodComponent',
        M_Route: 'M_Route',
        M_Modifier: 'M_Modifier',
        m_nanda_dignosis: 'M_Nanda_Diagnosis',
        m_nanda_domain: 'M_Nanda_Domain',
        m_nanda_class: 'M_Nanda_Class',
        M_Generic: 'M_Generic',
        vitals: 'Vital',
        m_labtest: 'M_LabTest',
        m_labCategory: 'M_labTestCategory',
        m_template_category: 'M_Template_Category',
        m_template_subcategory: 'M_Template_subcategory',
        m_frequency: 'M_Frequency',
        m_sample: 'M_Sample',
        m_specimen: 'M_Speciman',
        m_radiology: 'M_RadiologyTest',
        prefIcdCodes: 'prefIcdCodes',
        prefVitalSet: 'prefVitalSet',
        masterCounter: 'M_Counter',
        masterGender: 'M_gender',
        masterUserType: 'M_userType',
        m_TemplateImage:'M_AnnotationImage',
        depRelationship:'M_dependRelationship',
        //prefNotification:prefNotification,
        //notificationType:notificationType,
        m_dispensingtype:'m_dispensingtype',
        m_rehub:'m_rehabs',
        m_refferal_service:'m_referral_services',
        m_diet_types:'m_diet_types',
        m_enteral_nutritions:'m_enteral_nutritions',
        m_quick_links:'m_quick_links',
        m_drugmasters_new:'m_drugmasters_new',
        m_molecules:'m_molecules',
        m_dosefrequencydetails:'m_dosefrequencydetails',
        M_MedicationStatus:"M_MedicationStatus",
        M_Immunisations:"M_Immunisations",
        m_help_texts:"m_help_texts",
        m_nursing_orders:"m_nursing_orders",
        m_specimans:"m_specimans"
    }
};
